import React, { useState, useEffect } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { StyleSheet, Text, View, TouchableOpacity, ScrollView, ActivityIndicator, Alert, Image, Modal, TextInput, Dimensions, Platform, KeyboardAvoidingView, TouchableWithoutFeedback, Keyboard } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { doc, onSnapshot, collection, addDoc, Timestamp, query, orderBy, deleteDoc, updateDoc } from 'firebase/firestore';
import { ref, uploadBytes, getDownloadURL, deleteObject } from 'firebase/storage';
import { db, storage } from '../../config/firebaseConfig';

const SCREEN_WIDTH = Dimensions.get('window').width;
// ~30% of screen minus padding and gaps
const GRID_ITEM_SIZE = (SCREEN_WIDTH - 40 - 16) / 3;

// ─── Grouping Helper ──────────────────────────────────────────────────────────
function groupByMonth(docs: any[]) {
  const map: Record<string, any[]> = {};
  docs.forEach((d) => {
    const dateStr = d.date || '';
    const parsed = new Date(dateStr);
    const key = isNaN(parsed.getTime())
      ? 'Unknown Date'
      : parsed.toLocaleString('default', { month: 'long', year: 'numeric' });
    if (!map[key]) map[key] = [];
    map[key].push(d);
  });
  return Object.entries(map)
    .sort(([a], [b]) => new Date(b).getTime() - new Date(a).getTime())
    .map(([month, items]) => ({ month, items }));
}

export default function PetProfile() {
  // Grabs the exact document ID passed from the Dashboard
  const { id } = useLocalSearchParams(); 
  const router = useRouter();

  const [petData, setPetData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [selectedImageUri, setSelectedImageUri] = useState<string | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [medicalRecords, setMedicalRecords] = useState<any[]>([]);
  const [viewingImageUrl, setViewingImageUrl] = useState<string | null>(null);

  // Inline Editing State
  const [editingField, setEditingField] = useState<string | null>(null);
  const [editValue, setEditValue] = useState('');

  // Gallery State
  const [documents, setDocuments] = useState<any[]>([]);
  const [isCardLayout, setIsCardLayout] = useState(false);
  const [selectedDoc, setSelectedDoc] = useState<any>(null);
  const [collapsedMonths, setCollapsedMonths] = useState<string[]>([]);
  const [isEditingDoc, setIsEditingDoc] = useState(false);
  const [editTitle, setEditTitle] = useState('');
  const [editNote, setEditNote] = useState('');

  const toggleMonth = (month: string) => {
    setCollapsedMonths((prev) =>
      prev.includes(month) ? prev.filter((m) => m !== month) : [...prev, month]
    );
  };

  const groupedDocs = groupByMonth(documents);

  // ─── Documents Firestore Listener ─────────────────────────────────────────
  useEffect(() => {
    if (!id || typeof id !== 'string') return;
    const docsRef = collection(db, 'pets', id, 'documents');
    const q = query(docsRef, orderBy('date', 'desc'));
    const unsub = onSnapshot(q, (snap) => {
      setDocuments(snap.docs.map((d) => ({ id: d.id, ...d.data() })));
    }, (err) => console.error('Error fetching documents:', err));
    return () => unsub();
  }, [id]);

  // ─── Document CRUD ────────────────────────────────────────────────────────
  const handleDeleteDoc = async (docId: string) => {
    if (!docId) {
      Alert.alert('Error', 'Document ID is missing!');
      return;
    }
    const fullPath = `pets/${id}/documents/${docId}`;
    console.log('🗑️ handleDeleteDoc called — path:', fullPath);
    try {
      await deleteDoc(doc(db, 'pets', id as string, 'documents', docId));
      console.log('✅ Delete successful — path:', fullPath);
      setSelectedDoc(null);
    } catch (error: any) {
      console.error('❌ Firebase Delete Error — path:', fullPath, error);
      Alert.alert('Delete Failed', error.message);
    }
  };

  const handleSaveDocEdit = async () => {
    if (!selectedDoc) return;
    try {
      await updateDoc(doc(db, 'pets', id as string, 'documents', selectedDoc.id), {
        title: editTitle.trim(),
        note: editNote.trim(),
      });
      setIsEditingDoc(false);
      setSelectedDoc(null);
    } catch (err: any) {
      Alert.alert('Save Failed', err.message || 'Could not save changes.');
    }
  };

  const generateTestDoc = async () => {
    if (!id || typeof id !== 'string') return;
    try {
      await addDoc(collection(db, 'pets', id, 'documents'), {
        title: 'Test Vet Bill',
        note: 'Autogenerated note',
        date: new Date().toISOString().split('T')[0],
        thumbnailUrl: 'https://placehold.co/300x300/F0EBE6/A07850?text=Doc',
      });
    } catch (err: any) {
      Alert.alert('Error', err.message || 'Could not create test document.');
    }
  };

  const pickDocument = async () => {
    Alert.alert(
      'Upload Document',
      'Choose a method to upload the medical document',
      [
        {
          text: 'Camera',
          onPress: async () => {
            const { status } = await ImagePicker.requestCameraPermissionsAsync();
            if (status !== 'granted') {
              Alert.alert('Permission needed', 'Sorry, we need camera permissions to make this work!');
              return;
            }
            
            const result = await ImagePicker.launchCameraAsync({
              mediaTypes: ['images'],
              allowsEditing: true,
              quality: 0.7,
            });

            if (!result.canceled) {
              setSelectedImageUri(result.assets[0].uri);
            }
          }
        },
        {
          text: 'Photo Gallery',
          onPress: async () => {
            const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
            if (status !== 'granted') {
              Alert.alert('Permission needed', 'Sorry, we need camera roll permissions to make this work!');
              return;
            }

            const result = await ImagePicker.launchImageLibraryAsync({
              mediaTypes: ['images'],
              allowsEditing: true,
              quality: 0.7,
            });

            if (!result.canceled) {
              setSelectedImageUri(result.assets[0].uri);
            }
          }
        },
        {
          text: 'Cancel',
          style: 'cancel'
        }
      ]
    );
  };

  const uploadDocument = async () => {
    if (!selectedImageUri || !id || typeof id !== 'string') return;

    setIsUploading(true);

    try {
      // Convert image uri to Blob
      const response = await fetch(selectedImageUri);
      const blob = await response.blob();

      // Create storage reference
      const fileName = `doc_${Date.now()}.jpg`;
      const fileRef = ref(storage, `pets/${id}/medical_records/${fileName}`);

      // Upload file
      await uploadBytes(fileRef, blob);

      // Get securely hosted Download URL
      const downloadUrl = await getDownloadURL(fileRef);

      // Save record internally to Firestore Sub-collection
      await addDoc(collection(db, 'pets', id, 'medicalRecords'), {
        fileUrl: downloadUrl,
        uploadedAt: Timestamp.now(),
        type: 'Uncategorized'
      });

      Alert.alert('Success', 'Medical document saved successfully!');
      setSelectedImageUri(null);
    } catch (error: any) {
      console.error('Error uploading document:', error);
      Alert.alert('Upload Failed', error.message || 'An error occurred during upload.');
    } finally {
      setIsUploading(false);
    }
  };

  const deleteRecord = async (recordId: string, fileUrl?: string) => {
    Alert.alert(
      'Delete Document?',
      'Are you sure you want to permanently delete this medical record? This cannot be undone.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              if (fileUrl) {
                const fileRef = ref(storage, fileUrl);
                await deleteObject(fileRef);
              }
              await deleteDoc(doc(db, 'pets', id as string, 'medicalRecords', recordId));
            } catch (error: any) {
              console.error('Error deleting record:', error);
              Alert.alert('Delete Failed', error.message || 'An error occurred while deleting.');
            }
          }
        }
      ]
    );
  };

  const handleInlineSave = async () => {
    if (!editingField || !id || typeof id !== 'string') return;
    
    try {
      const petRef = doc(db, 'pets', id);
      await updateDoc(petRef, {
        [editingField]: editValue.trim()
      });
      setEditingField(null);
    } catch (error: any) {
      console.error('Error updating field:', error);
      Alert.alert('Update Failed', error.message || 'Could not save your changes.');
    }
  };

  const startEditing = (field: string, currentValue: string) => {
    setEditingField(field);
    setEditValue(currentValue || '');
  };

  useEffect(() => {
    if (!id || typeof id !== 'string') return;

    const docRef = doc(db, 'pets', id);
    const unsubscribePet = onSnapshot(docRef, (docSnap) => {
      if (docSnap.exists()) {
        setPetData({ id: docSnap.id, ...docSnap.data() });
      } else {
        console.log("No such document!");
      }
      setLoading(false);
    }, (error) => {
      console.error("Error fetching pet data: ", error);
      setLoading(false);
    });

    const recordsRef = collection(db, 'pets', id, 'medicalRecords');
    const q = query(recordsRef, orderBy('uploadedAt', 'desc'));
    const unsubscribeRecords = onSnapshot(q, (querySnapshot) => {
      const records: any[] = [];
      querySnapshot.forEach((docSnap) => {
        records.push({ id: docSnap.id, ...docSnap.data() });
      });
      setMedicalRecords(records);
    }, (error) => {
      console.error("Error fetching medical records: ", error);
    });

    return () => {
      unsubscribePet();
      unsubscribeRecords();
    };
  }, [id]);

  const handleOptions = (petId: string, petName: string) => {
    Alert.alert(
      `${petName} Options`,
      'What would you like to do?',
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Edit Pet', 
          onPress: () => router.push(`/pet/edit/${petId}`) 
        },
        {
          text: 'Delete Pet',
          style: 'destructive',
          onPress: () => {
            Alert.alert(
              `Delete ${petName}?`,
              'This action is permanent and will remove all associated medical records.',
              [
                { text: 'Cancel', style: 'cancel' },
                {
                  text: 'Yes, Delete',
                  style: 'destructive',
                  onPress: async () => {
                    try {
                      await deleteDoc(doc(db, 'pets', petId));
                      router.replace('/');
                    } catch (error: any) {
                      console.error('Delete error:', error);
                      Alert.alert('Error', 'Failed to delete pet: ' + error.message);
                    }
                  }
                }
              ]
            );
          }
        }
      ]
    );
  };

  if (loading) {
    return (
      <SafeAreaView style={[styles.container, { justifyContent: 'center', alignItems: 'center' }]}>
        <ActivityIndicator size="large" color="#FF6B6B" />
      </SafeAreaView>
    );
  }

  if (!petData) {
    return (
      <SafeAreaView style={[styles.container, { justifyContent: 'center', alignItems: 'center' }]}>
        <Text style={{ fontSize: 18, color: '#A09C98' }}>Pet not found.</Text>
        <TouchableOpacity style={{ marginTop: 20 }} onPress={() => router.back()}>
          <Text style={{ color: '#007AFF', fontSize: 16 }}>Go Back</Text>
        </TouchableOpacity>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
    <KeyboardAvoidingView
      style={{ flex: 1 }}
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
    >
      <TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
        <View style={{ flex: 1 }}>
      <StatusBar style="dark" />
      
      {/* Header Section */}
      <View style={styles.header}>
        <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
          <Text style={styles.backBtnText}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>{petData.name}&apos;s Profile</Text>
        <TouchableOpacity style={styles.headerOptionsBtn} onPress={() => handleOptions(petData.id, petData.name)}>
          <Text style={styles.headerOptionsText}>⋮</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.body} showsVerticalScrollIndicator={false}>
        
        {/* Profile Header */}
        <View style={styles.profileHeader}>
          <View style={styles.avatarPlaceholder}>
            <Text style={styles.avatarEmoji}>{petData.icon || '🐾'}</Text>
          </View>
          <Text style={styles.petName}>{petData.name}</Text>
          <Text style={{ fontSize: 16, color: '#666', marginBottom: 12 }}>{petData.species} | {petData.breed} | {petData.weight}</Text>
          <Text style={styles.statusBadge}>Status: Healthy</Text>
        </View>

        <View style={styles.actionRow}>
          <TouchableOpacity style={styles.shareBtn} onPress={() => router.push(`/pet/share/${petData.id}`)}>
            <Text style={styles.shareBtnText}>🔗 Share Profile</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.aiBtn} onPress={() => alert('Opening AI Assistant...')}>
            <Text style={styles.aiBtnText}>✨ Ask AI Vet</Text>
          </TouchableOpacity>
        </View>

        {/* Medical Scanner UI */}
        <View style={styles.section}>
          <TouchableOpacity style={styles.scanBtn} onPress={pickDocument}>
            <Text style={styles.scanBtnText}>📷 Scan/Upload Medical Document</Text>
          </TouchableOpacity>

          {selectedImageUri && (
            <View style={styles.previewContainer}>
              <Text style={styles.previewTitle}>Document Preview:</Text>
              <Image source={{ uri: selectedImageUri }} style={styles.previewImage} />
              <View style={styles.previewActions}>
                <TouchableOpacity 
                  style={[styles.saveBtn, isUploading && { opacity: 0.5 }]} 
                  onPress={uploadDocument}
                  disabled={isUploading}
                >
                  {isUploading ? (
                    <ActivityIndicator color="#FFF" />
                  ) : (
                    <Text style={styles.saveBtnText}>💾 Save Document</Text>
                  )}
                </TouchableOpacity>

                <TouchableOpacity 
                  style={styles.clearBtn} 
                  onPress={() => !isUploading && setSelectedImageUri(null)}
                  disabled={isUploading}
                >
                  <Text style={styles.clearBtnText}>Cancel/Clear</Text>
                </TouchableOpacity>
              </View>
            </View>
          )}
        </View>

        {/* Care Details Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Care Details</Text>
          <View style={styles.card}>
            
            {/* Diet Row */}
            <View style={styles.detailRow}>
              <View style={styles.detailContent}>
                <Text style={styles.detailLabel}>Diet</Text>
                {editingField === 'diet' ? (
                  <TextInput style={styles.inlineInput} value={editValue} onChangeText={setEditValue} autoFocus />
                ) : (
                  <Text style={styles.detailValue}>{petData.diet || 'None added'}</Text>
                )}
              </View>
              {editingField === 'diet' ? (
                <TouchableOpacity onPress={handleInlineSave}><Text style={styles.editActionText}>Save</Text></TouchableOpacity>
              ) : (
                <TouchableOpacity onPress={() => startEditing('diet', petData.diet)}><Text style={styles.editActionText}>Edit</Text></TouchableOpacity>
              )}
            </View>

            {/* Allergies Row */}
            <View style={styles.detailRow}>
              <View style={styles.detailContent}>
                <Text style={styles.detailLabel}>Allergies</Text>
                {editingField === 'allergies' ? (
                  <TextInput style={styles.inlineInput} value={editValue} onChangeText={setEditValue} autoFocus />
                ) : (
                  <Text style={styles.detailValue}>{petData.allergies || 'None added'}</Text>
                )}
              </View>
              {editingField === 'allergies' ? (
                <TouchableOpacity onPress={handleInlineSave}><Text style={styles.editActionText}>Save</Text></TouchableOpacity>
              ) : (
                <TouchableOpacity onPress={() => startEditing('allergies', petData.allergies)}><Text style={styles.editActionText}>Edit</Text></TouchableOpacity>
              )}
            </View>

            {/* Medications Row */}
            <View style={styles.detailRow}>
              <View style={styles.detailContent}>
                <Text style={styles.detailLabel}>Medications</Text>
                {editingField === 'medications' ? (
                  <TextInput style={styles.inlineInput} value={editValue} onChangeText={setEditValue} autoFocus />
                ) : (
                  <Text style={styles.detailValue}>{petData.medications || 'None added'}</Text>
                )}
              </View>
              {editingField === 'medications' ? (
                <TouchableOpacity onPress={handleInlineSave}><Text style={styles.editActionText}>Save</Text></TouchableOpacity>
              ) : (
                <TouchableOpacity onPress={() => startEditing('medications', petData.medications)}><Text style={styles.editActionText}>Edit</Text></TouchableOpacity>
              )}
            </View>

            {/* Sitter Notes Row */}
            <View style={styles.detailRow}>
              <View style={styles.detailContent}>
                <Text style={styles.detailLabel}>Sitter Notes</Text>
                {editingField === 'sitterNotes' ? (
                  <TextInput 
                    style={[styles.inlineInput, { minHeight: 60, textAlignVertical: 'top' }]} 
                    value={editValue} 
                    onChangeText={setEditValue} 
                    multiline 
                    autoFocus 
                  />
                ) : (
                  <Text style={styles.detailValue}>{petData.sitterNotes || 'None added'}</Text>
                )}
              </View>
              {editingField === 'sitterNotes' ? (
                <TouchableOpacity onPress={handleInlineSave}><Text style={styles.editActionText}>Save</Text></TouchableOpacity>
              ) : (
                <TouchableOpacity onPress={() => startEditing('sitterNotes', petData.sitterNotes)}><Text style={styles.editActionText}>Edit</Text></TouchableOpacity>
              )}
            </View>

          </View>
        </View>

        {/* ── Medical Documents Gallery ── */}
        <View style={styles.section}>

          {/* Master Header */}
          <View style={styles.galleryHeader}>
            <Text style={styles.sectionTitle}>Medical Documents</Text>
            <View style={styles.galleryHeaderRight}>
              {/* Test Doc generator */}
              <TouchableOpacity
                style={styles.testDocBtn}
                onPress={generateTestDoc}
                activeOpacity={0.75}
              >
                <Ionicons name='add' size={14} color='#888' />
                <Text style={styles.testDocBtnText}>Test Doc</Text>
              </TouchableOpacity>
              {/* Layout toggle */}
              <TouchableOpacity
                style={styles.layoutToggleBtn}
                onPress={() => setIsCardLayout((v) => !v)}
                activeOpacity={0.75}
              >
                <Ionicons
                  name={isCardLayout ? 'grid-outline' : 'list-outline'}
                  size={15}
                  color='#F79E44'
                />
                <Text style={styles.layoutToggleText}>
                  {isCardLayout ? 'Grid' : 'Cards'}
                </Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Grouped Sections */}
          {groupedDocs.map(({ month, items }) => {
            const isCollapsed = collapsedMonths.includes(month);
            return (
              <View key={month}>

                {/* Month/Year Header */}
                <TouchableOpacity
                  style={styles.monthHeader}
                  onPress={() => toggleMonth(month)}
                  activeOpacity={0.7}
                >
                  <Text style={styles.monthHeaderText}>{month}</Text>
                  <Ionicons
                    name={isCollapsed ? 'chevron-down' : 'chevron-up'}
                    size={16}
                    color='#888'
                  />
                </TouchableOpacity>

                {/* Documents */}
                {!isCollapsed && (
                  isCardLayout ? (
                    // ── Card (list) layout ──
                    <View style={styles.cardList}>
                      {items.map((doc) => (
                        <View key={doc.id} style={styles.docCard}>
                          <TouchableOpacity onPress={() => setViewingImageUrl(doc.thumbnailUrl)}>
                            <Image source={{ uri: doc.thumbnailUrl }} style={styles.docCardThumb} />
                          </TouchableOpacity>
                          <View style={styles.docCardMeta}>
                            <Text style={styles.docCardTitle} numberOfLines={1}>{doc.title}</Text>
                            <Text style={styles.docCardNote} numberOfLines={2}>{doc.note}</Text>
                            <Text style={styles.docCardDate}>{new Date(doc.date).toLocaleDateString()}</Text>
                          </View>
                          <TouchableOpacity
                            style={styles.dotsMenuBtn}
                            onPress={() => setSelectedDoc(doc)}
                          >
                            <Ionicons name='ellipsis-horizontal' size={18} color='#A09C98' />
                          </TouchableOpacity>
                        </View>
                      ))}
                    </View>
                  ) : (
                    // ── Grid layout ──
                    <View style={styles.gridContainer}>
                      {items.map((doc) => (
                        <View key={doc.id} style={styles.gridItem}>
                          <TouchableOpacity
                            style={styles.gridThumbContainer}
                            onPress={() => setViewingImageUrl(doc.thumbnailUrl)}
                            activeOpacity={0.85}
                          >
                            <Image source={{ uri: doc.thumbnailUrl }} style={styles.gridThumb} />
                            <TouchableOpacity
                              style={styles.gridDotsBtn}
                              onPress={() => setSelectedDoc(doc)}
                              hitSlop={{ top: 8, right: 8, bottom: 8, left: 8 }}
                            >
                              <Ionicons name='ellipsis-horizontal' size={14} color='#FFF' />
                            </TouchableOpacity>
                          </TouchableOpacity>
                          <Text style={styles.gridItemLabel} numberOfLines={1}>{doc.title}</Text>
                        </View>
                      ))}
                    </View>
                  )
                )}

              </View>
            );
          })}
        </View>

        {/* Bottom spacer so you can scroll past the last card comfortably */}
        <View style={{ height: 40 }} />
      </ScrollView>

      {/* Full-screen Image Viewer Modal */}
      <Modal visible={!!viewingImageUrl} transparent={true} animationType='fade'>
        <View style={styles.modalOverlay}>
          <TouchableOpacity style={styles.modalCloseBtn} onPress={() => setViewingImageUrl(null)}>
            <Text style={styles.modalCloseText}>Close</Text>
          </TouchableOpacity>
          {viewingImageUrl && (
            <Image source={{ uri: viewingImageUrl }} style={styles.modalImage} />
          )}
        </View>
      </Modal>

      {/* Document Options / Edit Modal */}
      <Modal
        visible={!!selectedDoc}
        transparent={true}
        animationType='slide'
        onRequestClose={() => { setIsEditingDoc(false); setSelectedDoc(null); }}
      >
        <TouchableOpacity
          style={styles.optionsOverlay}
          activeOpacity={1}
          onPress={() => { setIsEditingDoc(false); setSelectedDoc(null); }}
        >
          {/* KeyboardAvoidingView so inputs aren't hidden by keyboard in edit mode */}
          <KeyboardAvoidingView
            behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
            style={{ flex: 1, justifyContent: 'flex-end' }}
          >
            <TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
            <View
              style={styles.optionsSheet}
              onStartShouldSetResponder={() => true}
              onTouchEnd={(e) => e.stopPropagation()}
            >
            {/* Handle */}
            <View style={styles.optionsHandle} />

            {!isEditingDoc ? (
              // ── View mode ──────────────────────────────────────────────
              <>
                <Text style={styles.optionsTitle} numberOfLines={1}>
                  {selectedDoc?.title}
                </Text>
                <Text style={styles.optionsSubtitle}>{selectedDoc?.date}</Text>
                {selectedDoc?.note ? (
                  <Text style={styles.optionsNotePreview}>{selectedDoc.note}</Text>
                ) : null}

                <View style={styles.optionsDivider} />

                {/* Edit Details */}
                <TouchableOpacity
                  style={styles.optionsRow}
                  onPress={() => {
                    setEditTitle(selectedDoc?.title || '');
                    setEditNote(selectedDoc?.note || '');
                    setIsEditingDoc(true);
                  }}
                >
                  <Ionicons name='pencil-outline' size={20} color='#2D2926' style={styles.optionsRowIcon} />
                  <Text style={styles.optionsRowText}>Edit Details</Text>
                </TouchableOpacity>

                {/* Delete */}
                <TouchableOpacity
                  style={styles.optionsRow}
                  onPress={() => {
                    const docId = selectedDoc?.id;
                    const docTitle = selectedDoc?.title;
                    console.log('🔴 Delete button pressed — docId:', docId);

                    if (Platform.OS === 'web') {
                      // Alert.alert callbacks don't work on web — use browser confirm
                      const confirmed = window.confirm(
                        `Are you sure you want to delete "${docTitle}"? This cannot be undone.`
                      );
                      if (confirmed) {
                        setSelectedDoc(null);
                        handleDeleteDoc(docId);
                      }
                    } else {
                      Alert.alert(
                        'Delete Document',
                        `Are you sure you want to delete "${docTitle}"? This cannot be undone.`,
                        [
                          { text: 'Cancel', style: 'cancel' },
                          {
                            text: 'Delete',
                            style: 'destructive',
                            onPress: () => {
                              setSelectedDoc(null);
                              handleDeleteDoc(docId);
                            },
                          },
                        ]
                      );
                    }
                  }}
                >
                  <Ionicons name='trash-outline' size={20} color='#C62828' style={styles.optionsRowIcon} />
                  <Text style={[styles.optionsRowText, { color: '#C62828' }]}>Delete Document</Text>
                </TouchableOpacity>

                <View style={styles.optionsDivider} />

                <TouchableOpacity
                  style={[styles.optionsRow, { justifyContent: 'center' }]}
                  onPress={() => { setIsEditingDoc(false); setSelectedDoc(null); }}
                >
                  <Text style={styles.optionsCloseText}>Close</Text>
                </TouchableOpacity>
              </>
            ) : (
              // ── Edit mode ──────────────────────────────────────────────
              <>
                <Text style={styles.optionsTitle}>Edit Details</Text>
                <Text style={styles.optionsSubtitle}>Update title and note below</Text>

                <View style={styles.optionsDivider} />

                <Text style={styles.editInputLabel}>Title</Text>
                <TextInput
                  style={styles.editInput}
                  value={editTitle}
                  onChangeText={setEditTitle}
                  placeholder='Document title'
                  placeholderTextColor='#BBAFAA'
                />

                <Text style={[styles.editInputLabel, { marginTop: 12 }]}>Note</Text>
                <TextInput
                  style={[styles.editInput, { minHeight: 80, textAlignVertical: 'top' }]}
                  value={editNote}
                  onChangeText={setEditNote}
                  placeholder='Add a note…'
                  placeholderTextColor='#BBAFAA'
                  multiline
                />

                <View style={styles.optionsDivider} />

                {/* Save */}
                <TouchableOpacity
                  style={styles.saveEditBtn}
                  onPress={handleSaveDocEdit}
                >
                  <Text style={styles.saveEditBtnText}>Save Changes</Text>
                </TouchableOpacity>

                {/* Cancel */}
                <TouchableOpacity
                  style={[styles.optionsRow, { justifyContent: 'center', marginTop: 4 }]}
                  onPress={() => setIsEditingDoc(false)}
                >
                  <Text style={styles.optionsCloseText}>Cancel</Text>
                </TouchableOpacity>
              </>
            )}
          </View>
          </TouchableWithoutFeedback>
          </KeyboardAvoidingView>
        </TouchableOpacity>
      </Modal>

    </View>
      </TouchableWithoutFeedback>
    </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FDFBF9',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EBE6',
    backgroundColor: '#FFFFFF',
  },
  backBtn: {
    padding: 10,
    marginLeft: -10,
  },
  backBtnText: {
    fontSize: 16,
    color: '#007AFF', 
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2D2926',
    flex: 1,
    textAlign: 'center',
  },
  headerOptionsBtn: {
    padding: 10,
    marginRight: -10,
  },
  headerOptionsText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2D2926',
  },
  body: {
    paddingHorizontal: 20,
  },
  profileHeader: {
    alignItems: 'center',
    paddingTop: 30,
    paddingBottom: 20,
  },
  avatarPlaceholder: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#F0EBE6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  avatarEmoji: {
    fontSize: 45,
  },
  petName: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2D2926',
    marginBottom: 6,
  },
  statusBadge: {
    backgroundColor: '#E8F5E9', // Soft green
    color: '#2E7D32', // Dark green text
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    fontSize: 14,
    fontWeight: '600',
    overflow: 'hidden',
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 30,
  },
  shareBtn: {
    flex: 1,
    backgroundColor: '#F0EBE6',
    borderWidth: 1,
    borderColor: '#E0DBD6',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  shareBtnText: {
    color: '#2D2926',
    fontSize: 14,
    fontWeight: 'bold',
  },
  aiBtn: {
    flex: 1,
    backgroundColor: '#2D2926',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  aiBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#FDFBF9',
    paddingBottom: 8,
  },
  detailContent: {
    flex: 1,
    marginRight: 10,
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#888',
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 16,
    color: '#2D2926',
    lineHeight: 22,
  },
  inlineInput: {
    borderWidth: 1,
    borderColor: '#F0EBE6',
    borderRadius: 8,
    padding: 8,
    fontSize: 16,
    color: '#2D2926',
    backgroundColor: '#FDFBF9',
  },
  editActionText: {
    color: '#F79E44',
    fontWeight: 'bold',
    fontSize: 16,
    marginTop: 2,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D2926',
    marginBottom: 12,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#F0EBE6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  recordRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  recordName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D2926',
  },
  recordStatus: {
    fontSize: 12,
    color: '#2E7D32',
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  recordStatusAction: {
    fontSize: 12,
    color: '#C62828', // Red for alert
    backgroundColor: '#FFEBEE',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  recordDate: {
    fontSize: 14,
    color: '#888',
    marginTop: 2,
  },
  noteText: {
    fontSize: 14,
    color: '#666',
    marginTop: 8,
    lineHeight: 20,
  },
  documentActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  thumbnailImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    resizeMode: 'cover',
    backgroundColor: '#F0EBE6',
  },
  deleteBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#FFEBEE',
    borderRadius: 8,
  },
  deleteBtnText: {
    color: '#C62828',
    fontWeight: '600',
    fontSize: 14,
  },
  scanBtn: {
    backgroundColor: '#F0EBE6',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E0DBD6',
  },
  scanBtnText: {
    color: '#2D2926',
    fontSize: 16,
    fontWeight: '600',
  },
  previewContainer: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F0EBE6',
    marginBottom: 16,
  },
  previewTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#2D2926',
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  previewImage: {
    width: '100%',
    height: 300,
    borderRadius: 8,
    marginBottom: 16,
    resizeMode: 'contain',
    backgroundColor: '#000',
  },
  previewActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  saveBtn: {
    backgroundColor: '#2D2926',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  saveBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  clearBtn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#FFEBEE',
    borderRadius: 8,
  },
  clearBtnText: {
    color: '#C62828',
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseBtn: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 10,
    padding: 10,
  },
  modalCloseText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalImage: {
    width: '100%',
    height: '80%',
    resizeMode: 'contain',
  },

  // ── Gallery ──
  galleryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  layoutToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#FFF2E5',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F79E44',
  },
  layoutToggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#F79E44',
  },
  monthHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EBE6',
  },
  monthHeaderText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#A07850',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },

  // Card list
  cardList: {
    gap: 10,
    marginBottom: 18,
  },
  docCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#F0EBE6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  docCardThumb: {
    width: 60,
    height: 60,
    borderRadius: 10,
    backgroundColor: '#F0EBE6',
    marginRight: 12,
  },
  docCardMeta: {
    flex: 1,
  },
  docCardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2D2926',
    marginBottom: 2,
  },
  docCardNote: {
    fontSize: 13,
    color: '#888',
    lineHeight: 18,
    marginBottom: 4,
  },
  docCardDate: {
    fontSize: 12,
    color: '#BBAFAA',
    fontWeight: '500',
  },
  dotsMenuBtn: {
    padding: 8,
  },

  // Grid
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 18,
  },
  gridItem: {
    width: GRID_ITEM_SIZE,
  },
  gridThumbContainer: {
    width: GRID_ITEM_SIZE,
    height: GRID_ITEM_SIZE,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#F0EBE6',
  },
  gridThumb: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  gridDotsBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: 10,
    padding: 3,
  },
  gridItemLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#2D2926',
    marginTop: 5,
    paddingHorizontal: 2,
  },

  // Options Modal
  optionsOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  optionsSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 40,
    paddingTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 10,
  },
  optionsHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E0DBD6',
    alignSelf: 'center',
    marginBottom: 20,
  },
  optionsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2D2926',
    marginBottom: 2,
  },
  optionsSubtitle: {
    fontSize: 13,
    color: '#888',
    marginBottom: 16,
  },
  optionsDivider: {
    height: 1,
    backgroundColor: '#F0EBE6',
    marginVertical: 8,
  },
  optionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  optionsRowDestructive: {
    // tint applied via inline style on text
  },
  optionsRowIcon: {
    marginRight: 14,
  },
  optionsRowText: {
    fontSize: 16,
    color: '#2D2926',
    fontWeight: '500',
  },
  optionsCloseText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#888',
  },
  optionsNotePreview: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    marginBottom: 4,
    fontStyle: 'italic',
  },

  // Gallery header extras
  galleryHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  testDocBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E0DBD6',
  },
  testDocBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#888',
  },

  // Edit-mode inputs inside modal
  editInputLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#888',
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  editInput: {
    borderWidth: 1,
    borderColor: '#F0EBE6',
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    color: '#2D2926',
    backgroundColor: '#FDFBF9',
  },
  saveEditBtn: {
    backgroundColor: '#F79E44',
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  saveEditBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
});